
movies_dict = [
    {"id": 1, 
     "title": "El Padrino", 
     "overview": "La historia de una familia mafiosa en Nueva York.",
     "year": 1972, 
     "rating": 9.2,
     "category": "Drama"},
    {"id": 2,           
    "titel": "The Dark Knight", 
    "overview": "Batman enfrenta al Joker en Gotham City.",
    "year": 2008,           
    "rating": 9.0,
     "category": "Action"},
    {"id": 3, 
     "title": "Inception", 
     "overview": "Un ladrón que roba secretos a través de los sueños.",
     "year": 2010, 
     "rating": 8.8,
     "category": "Sci-Fi"},
    {"id": 4, 
     "title": "Forrest Gump", 
     "overview": "La vida extraordinaria de un hombre común.",
     "year": 1994, 
     "rating": 8.8,
     "category": "Drama"},
    {"id": 5, 
     "title": "The Matrix", 
     "overview": "Un hacker descubre la verdadera naturaleza de su realidad.",
     "year": 1999, 
     "rating": 8.7,
     "category": "Sci-Fi"} 
]